# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d1f0e2320eadf5c63866abe540cf6f6"
name = "multi-work-example"
handle = "multi-work-example"
application_url = "https://alive-slide-vacation-safer.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://alive-slide-vacation-safer.trycloudflare.com/auth/callback",
  "https://alive-slide-vacation-safer.trycloudflare.com/auth/shopify/callback",
  "https://alive-slide-vacation-safer.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
